// @ts-ignore - generated by @opennextjs/cloudflare after the Next.js build
import openNextWorker from "./.open-next/worker.js";

const DEEPSEEK_PROXY_PREFIX = "/api/deepseek";
const DEFAULT_DEEPSEEK_URL = "https://api.deepseek.com";

function hasCloudflareAccessIdentity(request: Request) {
  return Boolean(
    request.headers.get("cf-access-authenticated-user-email") ||
      request.headers.get("cf-access-jwt-assertion"),
  );
}

function errorResponse(message: string, status = 500) {
  return new Response(JSON.stringify({ error: true, message }), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

async function proxyDeepSeek(request: Request, env: any) {
  const requestUrl = new URL(request.url);
  const upstreamPath =
    requestUrl.pathname.slice(DEEPSEEK_PROXY_PREFIX.length) || "/";

  let baseUrl = String(env.DEEPSEEK_URL || DEFAULT_DEEPSEEK_URL).trim();
  if (!baseUrl.startsWith("http://") && !baseUrl.startsWith("https://")) {
    baseUrl = `https://${baseUrl}`;
  }
  baseUrl = baseUrl.replace(/\/$/, "");

  const apiKey = String(env.DEEPSEEK_API_KEY || "").trim();
  if (!apiKey) {
    return errorResponse("DEEPSEEK_API_KEY is not configured", 500);
  }

  const upstreamUrl = `${baseUrl}${upstreamPath}${requestUrl.search}`;
  const isAnthropicRequest = upstreamPath.startsWith("/anthropic/");
  const headers = new Headers();

  headers.set(
    "Content-Type",
    request.headers.get("content-type") || "application/json",
  );

  const accept = request.headers.get("accept");
  if (accept) headers.set("Accept", accept);

  if (isAnthropicRequest) {
    headers.set("x-api-key", apiKey);
    headers.set(
      "anthropic-version",
      request.headers.get("anthropic-version") || "2023-06-01",
    );
  } else {
    headers.set("Authorization", `Bearer ${apiKey}`);
  }

  const init: RequestInit & { duplex?: "half" } = {
    method: request.method,
    headers,
    redirect: "manual",
    signal: request.signal,
  };

  if (request.method !== "GET" && request.method !== "HEAD") {
    // Keep the large chat payload as a stream. Do not call text(), json(),
    // arrayBuffer(), clone(), or JSON.parse() in the Worker.
    init.body = request.body;
    init.duplex = "half";
  }

  try {
    const upstream = await fetch(upstreamUrl, init);
    const responseHeaders = new Headers(upstream.headers);
    responseHeaders.delete("www-authenticate");
    responseHeaders.set("X-Accel-Buffering", "no");
    responseHeaders.set("Cache-Control", "no-store");

    // Preserve DeepSeek SSE/body streaming all the way back to the browser.
    return new Response(upstream.body, {
      status: upstream.status,
      statusText: upstream.statusText,
      headers: responseHeaders,
    });
  } catch (error) {
    if (request.signal.aborted) {
      return errorResponse("DeepSeek request aborted", 499);
    }

    console.error("[Raw DeepSeek Proxy]", error);
    return errorResponse(
      error instanceof Error ? error.message : String(error),
      502,
    );
  }
}

export default {
  async fetch(request: Request, env: any, ctx: any) {
    const url = new URL(request.url);

    // The custom domain is protected by Cloudflare Access. For those requests,
    // bypass the Next.js/OpenNext route layer entirely so very large chat
    // histories do not spend the Free-plan CPU budget in framework routing.
    // workers.dev requests without Access keep using the existing Next handler.
    if (
      url.pathname.startsWith(`${DEEPSEEK_PROXY_PREFIX}/`) &&
      hasCloudflareAccessIdentity(request)
    ) {
      return proxyDeepSeek(request, env);
    }

    return openNextWorker.fetch(request, env, ctx);
  },
};
