// @ts-ignore - generated by @opennextjs/cloudflare after the Next.js build
import openNextWorker from "./.open-next/worker.js";

const DEEPSEEK_PROXY_PREFIX = "/api/deepseek";
const DEFAULT_DEEPSEEK_URL = "https://api.deepseek.com";
const ACCESS_CODE_PREFIX = "nk-";

function errorResponse(message: string, status = 500) {
  return new Response(JSON.stringify({ error: true, message }), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

function parseBearer(request: Request) {
  return (request.headers.get("Authorization") || "")
    .replace(/^Bearer\s+/i, "")
    .trim();
}

function authorizeDeepSeek(request: Request, env: any) {
  const token = parseBearer(request);
  const isAccessCode = token.startsWith(ACCESS_CODE_PREFIX);
  const accessCode = isAccessCode ? token.slice(ACCESS_CODE_PREFIX.length) : "";
  const isUserApiKey = Boolean(token) && !isAccessCode;
  const configuredCodes = String(env.CODE || "")
    .split(",")
    .map((code) => code.trim())
    .filter(Boolean);

  // Match the existing NextChat auth behavior without importing the Next.js
  // auth stack. When CODE is configured, a valid nk- access code is required.
  if (configuredCodes.length > 0 && !configuredCodes.includes(accessCode)) {
    return {
      ok: false,
      response: errorResponse(
        accessCode ? "wrong access code" : "empty access code",
        401,
      ),
    };
  }

  // Preserve HIDE_USER_API_KEY: do not let callers turn this endpoint into a
  // proxy for arbitrary user-supplied DeepSeek keys.
  if (env.HIDE_USER_API_KEY && isUserApiKey) {
    return {
      ok: false,
      response: errorResponse(
        "you are not allowed to access with your own api key",
        401,
      ),
    };
  }

  return { ok: true as const };
}

async function proxyDeepSeek(request: Request, env: any) {
  const auth = authorizeDeepSeek(request, env);
  if (!auth.ok) return auth.response;

  const requestUrl = new URL(request.url);
  const upstreamPath =
    requestUrl.pathname.slice(DEEPSEEK_PROXY_PREFIX.length) || "/";

  let baseUrl = String(env.DEEPSEEK_URL || DEFAULT_DEEPSEEK_URL).trim();
  if (!baseUrl.startsWith("http://") && !baseUrl.startsWith("https://")) {
    baseUrl = `https://${baseUrl}`;
  }
  baseUrl = baseUrl.replace(/\/$/, "");

  const apiKey = String(env.DEEPSEEK_API_KEY || "").trim();
  if (!apiKey) {
    return errorResponse("DEEPSEEK_API_KEY is not configured", 500);
  }

  const upstreamUrl = `${baseUrl}${upstreamPath}${requestUrl.search}`;
  const isAnthropicRequest = upstreamPath.startsWith("/anthropic/");
  const headers = new Headers();

  headers.set(
    "Content-Type",
    request.headers.get("content-type") || "application/json",
  );

  const accept = request.headers.get("accept");
  if (accept) headers.set("Accept", accept);

  if (isAnthropicRequest) {
    headers.set("x-api-key", apiKey);
    headers.set(
      "anthropic-version",
      request.headers.get("anthropic-version") || "2023-06-01",
    );
  } else {
    headers.set("Authorization", `Bearer ${apiKey}`);
  }

  const init: RequestInit & { duplex?: "half" } = {
    method: request.method,
    headers,
    redirect: "manual",
    signal: request.signal,
  };

  if (request.method !== "GET" && request.method !== "HEAD") {
    // Critical for long conversations: keep the request body as a stream.
    // Never call text(), json(), arrayBuffer(), clone() or JSON.parse() here.
    init.body = request.body;
    init.duplex = "half";
  }

  try {
    const upstream = await fetch(upstreamUrl, init);
    const responseHeaders = new Headers(upstream.headers);
    responseHeaders.delete("www-authenticate");
    responseHeaders.set("X-Accel-Buffering", "no");
    responseHeaders.set("Cache-Control", "no-store");

    // Stream DeepSeek SSE/body back unchanged. No buffering or parsing in the
    // Worker, so request CPU cost stays nearly independent of history length.
    return new Response(upstream.body, {
      status: upstream.status,
      statusText: upstream.statusText,
      headers: responseHeaders,
    });
  } catch (error) {
    if (request.signal.aborted) {
      return errorResponse("DeepSeek request aborted", 499);
    }

    console.error("[Raw DeepSeek Proxy]", error);
    return errorResponse(
      error instanceof Error ? error.message : String(error),
      502,
    );
  }
}

export default {
  async fetch(request: Request, env: any, ctx: any) {
    const url = new URL(request.url);

    // DeepSeek is the heavy long-context path. Bypass Next.js/OpenNext for it
    // on BOTH the custom domain and workers.dev. Other UI/API requests still
    // use the normal OpenNext worker.
    if (url.pathname.startsWith(`${DEEPSEEK_PROXY_PREFIX}/`)) {
      return proxyDeepSeek(request, env);
    }

    return openNextWorker.fetch(request, env, ctx);
  },
};
