const DEEPSEEK_PROXY_PREFIX = "/api/deepseek";
const D1_SYNC_PATH = "/api/sync/d1";
const EDGE_API_BINDING = "NEXTCHAT_EDGE_API";

type OpenNextWorker = {
  fetch(request: Request, env: any, ctx: any): Response | Promise<Response>;
};

let openNextWorkerPromise: Promise<OpenNextWorker> | null = null;

function serviceError(message: string, status = 502) {
  return new Response(JSON.stringify({ error: true, message }), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      "X-NextChat-Service-Binding": "error",
    },
  });
}

function getOpenNextWorker() {
  if (!openNextWorkerPromise) {
    const startedAt = Date.now();
    console.log("[NextChat Gateway] loading OpenNext");

    // `.open-next/worker.js` is generated by @opennextjs/cloudflare before
    // Wrangler deploys this entrypoint. Keep it as a runtime module so API/D1
    // requests do not initialize the large OpenNext application bundle.
    // @ts-ignore - generated after the Next.js/OpenNext build step
    openNextWorkerPromise = import("./.open-next/worker.js")
      .then((module) => {
        const worker = module.default as OpenNextWorker;
        if (!worker?.fetch) {
          throw new Error("Generated OpenNext worker does not export fetch()");
        }
        console.log("[NextChat Gateway] OpenNext loaded", {
          durationMs: Date.now() - startedAt,
        });
        return worker;
      })
      .catch((error) => {
        openNextWorkerPromise = null;
        console.error("[NextChat Gateway] OpenNext load failed", error);
        throw error;
      });
  }

  return openNextWorkerPromise;
}

async function forwardToEdgeApi(request: Request, env: any) {
  const url = new URL(request.url);
  const requestId = request.headers.get("cf-ray") || crypto.randomUUID();
  const edgeApi = env?.[EDGE_API_BINDING];

  console.log("[NextChat Gateway] edge request", {
    requestId,
    method: request.method,
    pathname: url.pathname,
  });

  if (!edgeApi?.fetch) {
    console.error("[NextChat Gateway] edge binding unavailable", {
      requestId,
      binding: EDGE_API_BINDING,
    });
    return serviceError(
      `Service binding ${EDGE_API_BINDING} is unavailable`,
      503,
    );
  }

  try {
    const response = await edgeApi.fetch(request);
    console.log("[NextChat Gateway] edge response", {
      requestId,
      pathname: url.pathname,
      status: response.status,
    });

    const headers = new Headers(response.headers);
    headers.set("X-NextChat-Service-Binding", "nextchat-edge-api");

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  } catch (error) {
    console.error("[NextChat Gateway] edge failure", {
      requestId,
      pathname: url.pathname,
      error: error instanceof Error ? error.message : String(error),
    });
    return serviceError(
      error instanceof Error ? error.message : String(error),
      502,
    );
  }
}

export default {
  async fetch(request: Request, env: any, ctx: any) {
    const url = new URL(request.url);

    if (url.pathname.startsWith(`${DEEPSEEK_PROXY_PREFIX}/`)) {
      return forwardToEdgeApi(request, env);
    }

    if (url.pathname === D1_SYNC_PATH || url.pathname === `${D1_SYNC_PATH}/`) {
      return forwardToEdgeApi(request, env);
    }

    const openNextWorker = await getOpenNextWorker();
    return openNextWorker.fetch(request, env, ctx);
  },
};
